name: Test
on:
  workflow_call:
    secrets:
      github-token:
        description: |
          The token to use to make authenticated GitHub API calls.
        required: true
jobs:
  test-powershell-desktop:
    name: Test with PowerShell Desktop
    runs-on: windows-latest
    steps:
      - id: checkout-bucket
        name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: .\custom_bucket\
          token: ${{secrets.github-token}}
      - id: checkout-scoop
        name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
          token: ${{secrets.github-token}}
      - id: override-tests
        name: Override Scoop Test(s)
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')";
          Copy-Item -Force .\custom_bucket\overrides\test\*.ps1 .\scoop_core\test\;
      - id: init-and-test
        name: Init and Test Bucket
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')";
          .\scoop_core\test\bin\init.ps1;
          .\my_bucket\bin\test.ps1;
  test-powershell-core:
    name: Test with PowerShell Core
    runs-on: windows-latest
    steps:
      - id: checkout-bucket
        name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: .\custom_bucket\
          token: ${{secrets.github-token}}
      - id: checkout-scoop
        name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
          token: ${{secrets.github-token}}
      - id: override-tests
        name: Override Scoop Test(s)
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')";
          Copy-Item -Force .\custom_bucket\overrides\test\*.ps1 .\scoop_core\test\;
      - id: init-and-test
        name: Init and Test Bucket
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"l;
          .\scoop_core\test\bin\init.ps1;
          .\custom_bucket\bin\test.ps1;
